/* confdefs.h */
#define PACKAGE_NAME "binwalk"
#define PACKAGE_TARNAME "binwalk"
#define PACKAGE_VERSION "0.3.8b"
#define PACKAGE_STRING "binwalk 0.3.8b"
#define PACKAGE_BUGREPORT "http://code.google.com/p/binwalk/issues/list"
#define PACKAGE_URL ""
#define HAVE_LIBCURL 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_ARPA_INET_H 1
#define HAVE_FCNTL_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_UNISTD_H 1
#define HAVE_CURL_CURL_H 1
#define HAVE_STDLIB_H 1
#define HAVE_MALLOC 1
#define HAVE_MEMSET 1
#define HAVE_STRDUP 1
#define HAVE_STRSTR 1
#define HAVE_STRTOL 1
