
# Copyright (C) 2006 Junjiro Okajima
# Copyright (C) 2006 Tomas Matejicek, slax.org
#
# LICENSE follows the described one in lzma.txt.

# $Id: Makefile,v 1.1.1.1 2007-06-05 09:36:21 steven Exp $

obj-m += unlzma.o sqlzma.o
unlzma-y := module.o
sqlzma-y := uncomp.o
