all:
	make -C ./squashfs-3.0-e2100
	make -C ./squashfs-3.2-r2
	make -C ./squashfs-3.2-r2-lzma
	make -C ./squashfs-3.2-r2-hg612-lzma
	make -C ./squashfs-3.3
	make -C ./squashfs-3.3-lzma
	make -C ./squashfs-3.3-grml-lzma
	make -C ./squashfs-4.0-lzma
	make -C ./squashfs-4.0-realtek

clean:
	make -C ./squashfs-3.0-e2100 clean
	make -C ./squashfs-3.2-r2 clean
	make -C ./squashfs-3.2-r2-lzma clean
	make -C ./squashfs-3.2-r2-hg612-lzma clean
	make -C ./squashfs-3.3 clean
	make -C ./squashfs-3.3-lzma clean
	make -C ./squashfs-3.3-grml-lzma clean
	make -C ./squashfs-4.0-lzma clean
	make -C ./squashfs-4.0-realtek clean
