#!/bin/bash
# Script to mount a JFFS2 image and copy the file system's files to a destination directory.
#
# Craig Heffner
# 27 August 2011

IMG="$1"
DST="$2"
BLOCK="/dev/mtdblock0"

if [ "$IMG" == "" ] || [ "$IMG" == "-h" ]
then
	echo "Usage: $0 <jffs2 image> [output directory]"
	exit 1
fi

if [ "$DST" == "" ]
then
	DST="jffs2-root"
fi

TMP="/tmp/$DST"

#Make sure required modules are loaded
modprobe mtdblock
modprobe mtdchar
modprobe mtdram
modprobe mtd

#Create destination and temporary mount directories
mkdir $DST && mkdir $TMP

if [ $? == 0 ]
then
	if [ ! -e $BLOCK ]
	then
		mknod $BLOCK b 31 0
	fi

	#Copy JFSS2 image to MTD block
	dd if="$IMG" of=$BLOCK 2>/dev/null && mount -t jffs2 $BLOCK $TMP

	if [ $? == 0 ]
	then
		#Copy files from mounted directory to destination directory, then unmount
		cp -vR $TMP/* $DST
		umount $TMP && rm -rf $TMP
		exit 0
	else
		echo "Failed to mount $IMG to $BLOCK"
	fi
fi

exit 1
